/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function WaterAnimationModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models-3d/WaterAnimation.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Text"
              position={[0, 0.138, -0.485]}
              rotation={[-1.571, 0, -Math.PI]}
              scale={1.136}
            />
            <RigidBody type="kinematicPosition" colliders="cuboid">
              <group name="waterKeyShapes" position={[-0.001, 0.134, 0.114]}>
                <mesh
                  name="waterKeyShapes_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.waterKeyShapes_0.geometry}
                  material={materials.waterKeyShapes}
                  morphTargetDictionary={nodes.waterKeyShapes_0.morphTargetDictionary}
                  morphTargetInfluences={nodes.waterKeyShapes_0.morphTargetInfluences}
                  scale={6}
                />
              </group>
            </RigidBody>
          </group>
        </group>
        <group name="ground" position={[0.008, -0.046, 0.08]} rotation={[3.097, -0.011, -0.008]}>
          <mesh
            name="ground_0"
            castShadow
            receiveShadow
            geometry={nodes.ground_0.geometry}
            material={materials.Stone}
            position={[-0.003, 0.396, 0.018]}
          />
          <mesh
            name="ground_1"
            castShadow
            receiveShadow
            geometry={nodes.ground_1.geometry}
            material={materials.Sticks}
            position={[-0.003, 0.396, 0.018]}
          />
          <mesh
            name="ground_2"
            castShadow
            receiveShadow
            geometry={nodes.ground_2.geometry}
            material={materials.Plants}
            position={[-0.003, 0.396, 0.018]}
          />
          <mesh
            name="ground_3"
            castShadow
            receiveShadow
            geometry={nodes.ground_3.geometry}
            material={materials.Ground}
            position={[-0.003, 0.396, 0.018]}
          />
          <group name="plant" position={[-0.02, 0.452, 0.064]} rotation={[3.03, 1.008, -3.116]}>
            <mesh
              name="plant_0"
              castShadow
              receiveShadow
              geometry={nodes.plant_0.geometry}
              material={materials.flower_bark}
            />
            <mesh
              name="plant_1"
              castShadow
              receiveShadow
              geometry={nodes.plant_1.geometry}
              material={materials.fan_plant}
            />
          </group>
          <group name="tree001" position={[-0.084, -0.129, 0.018]} rotation={[1.593, -1.48, 1.247]}>
            <mesh
              name="tree001_0"
              castShadow
              receiveShadow
              geometry={nodes.tree001_0.geometry}
              material={materials.lambert2SG}
            />
            <mesh
              name="tree001_1"
              castShadow
              receiveShadow
              geometry={nodes.tree001_1.geometry}
              material={materials.lambert5SG}
            />
            <mesh
              name="tree001_2"
              castShadow
              receiveShadow
              geometry={nodes.tree001_2.geometry}
              material={materials.lambert3SG}
            />
            <mesh
              name="tree001_3"
              castShadow
              receiveShadow
              geometry={nodes.tree001_3.geometry}
              material={materials.initialShadingGroup}
            />
          </group>
        </group>
        <group name="loggerheadbody" />
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/WaterAnimation.glb')