import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HomeRiverModel(props) {
  const { nodes, materials } = useGLTF('/models-3d/HomeRiver.glb')
  return (
    <group {...props} dispose={null} scale={0.1} rotation={[0, 1.55, 0]}>
      <group position={[0, -0.347, -1.622]} scale={[1, 0.835, 0.889]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert21_0.geometry}
          material={materials.lambert21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube2_lambert21_0.geometry}
          material={materials.lambert21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder10_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder11_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder12_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder5_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder6_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder7_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder8_lambert22_0.geometry}
          material={materials.lambert22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder9_lambert22_0.geometry}
          material={materials.lambert22}
        />
      </group>
      <group
        position={[-33.413, 0.616, -44.247]}
        rotation={[0, 0.428, 0]}
        scale={[1.268, 1.476, 1.476]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0.geometry}
          material={materials.lambert17}
        />
      </group>
      <group
        position={[-33.413, 0.616, 57.231]}
        rotation={[0, -0.004, 0]}
        scale={[1.268, 1.476, 1.476]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0001.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0001.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0001.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0001.geometry}
          material={materials.lambert17}
        />
      </group>
      <group
        position={[-33.413, 0.616, 57.231]}
        rotation={[0, -0.004, 0]}
        scale={[1.268, 1.476, 1.476]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0002.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0002.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0002.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0002.geometry}
          material={materials.lambert17}
        />
      </group>
      <group
        position={[-0.345, 15.549, 42.309]}
        rotation={[0, -0.004, 0]}
        scale={[1.268, 1.476, 1.476]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0003.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0003.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0003.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0003.geometry}
          material={materials.lambert17}
        />
      </group>
      <group
        position={[-7.029, 1.75, -1.685]}
        rotation={[0, -0.328, 0]}
        scale={[1.268, 1.476, 1.476]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0004.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0004.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0004.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0004.geometry}
          material={materials.lambert17}
        />
      </group>
      <group
        position={[-6.737, 4.588, 5.004]}
        rotation={[0, 0.216, 0]}
        scale={[1.537, 1.789, 1.789]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic19_lambert17_0005.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic20_lambert17_0005.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic21_lambert17_0005.geometry}
          material={materials.lambert17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic22_lambert17_0005.geometry}
          material={materials.lambert17}
        />
      </group>
      <group position={[-14.479, -0.704, 33.225]} rotation={[0, -0.833, 0]} scale={0.834}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube10_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_lambert24_0.geometry}
          material={materials.lambert24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_lambert24_0.geometry}
          material={materials.lambert24}
        />
      </group>
      <group position={[1.668, -3.323, 3.423]} rotation={[Math.PI, -0.704, Math.PI]} scale={11.476}>
        <group position={[3.734, -1.198, -0.532]} rotation={[Math.PI, -1.4, Math.PI]} scale={0.409}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube1_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube2_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube3_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube4_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube5_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder2_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder3_pasted__lambert10_0.geometry}
            material={materials.pasted__lambert10}
          />
        </group>
      </group>
      <group position={[-41.218, 0, -34.787]} rotation={[0, 1.357, 0]}>
        <group position={[-42.757, -1.227, 27.25]} scale={0.831}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder2_tree_trunk_0007.geometry}
            material={materials.tree_trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic10_lambert9_0007.geometry}
            material={materials.lambert9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic11_lambert8_0007.geometry}
            material={materials.lambert8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic12_lambert8_0007.geometry}
            material={materials.lambert8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic13_lambert7_0007.geometry}
            material={materials.lambert7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic14_lambert7_0007.geometry}
            material={materials.lambert7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic15_lambert7_0007.geometry}
            material={materials.lambert7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic16_lambert7_0007.geometry}
            material={materials.lambert7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic17_lambert8_0007.geometry}
            material={materials.lambert8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic18_lambert8_0007.geometry}
            material={materials.lambert8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic6_lambert9_0007.geometry}
            material={materials.lambert9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic7_lambert9_0007.geometry}
            material={materials.lambert9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic8_lambert9_0007.geometry}
            material={materials.lambert9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic9_lambert10_0007.geometry}
            material={materials.lambert10}
          />
        </group>
        <group position={[-47.883, -0.635, 37.907]} scale={1.052}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1_lambert18_0006.geometry}
            material={materials.lambert18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic1_lambert11_0006.geometry}
            material={materials.lambert11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic2_lambert11_0006.geometry}
            material={materials.lambert11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic3_lambert11_0006.geometry}
            material={materials.lambert11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic4_lambert11_0006.geometry}
            material={materials.lambert11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlatonic5_lambert11_0006.geometry}
            material={materials.lambert11}
          />
        </group>
      </group>
      <group position={[-17.817, -1.047, 105.073]} scale={1.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[28.026, 9.764, 27.125]} scale={1.901}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0001.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0001.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0001.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0001.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0001.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[-2.182, 8.7, 66.395]} scale={1.385}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0002.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0002.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0002.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0002.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0002.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[-57.867, -1.047, -9.349]} scale={1.106}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0003.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0003.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0003.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0003.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0003.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[61.95, 36.166, 70.13]} scale={1.385}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0004.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0004.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0004.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0004.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0004.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[19.36, 5.124, 91.961]} scale={1.385}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0005.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0005.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0005.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0005.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0005.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[28.091, 11.432, 35.543]} scale={1.565}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_lambert15_0006.geometry}
          material={materials.lambert15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone2_lambert14_0006.geometry}
          material={materials.lambert14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone3_lambert13_0006.geometry}
          material={materials.lambert13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone4_lambert12_0006.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert16_0006.geometry}
          material={materials.lambert16}
        />
      </group>
      <group position={[-19.372, 0, -24.064]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[29.519, 4.822, 43.838]} scale={1.216}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0001.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0001.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0001.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0001.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0001.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0001.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0001.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0001.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0001.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0001.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0001.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0001.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0001.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0001.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[44.595, 10.171, 6.887]} scale={1.352}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0002.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0002.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0002.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0002.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0002.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0002.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0002.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0002.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0002.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0002.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0002.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0002.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0002.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0002.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-2.705, 6.552, 71.244]} scale={0.831}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0003.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0003.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0003.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0003.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0003.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0003.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0003.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0003.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0003.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0003.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0003.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0003.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0003.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0003.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[19.872, 5.002, 4.066]} scale={0.831}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0004.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0004.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0004.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0004.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0004.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0004.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0004.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0004.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0004.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0004.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0004.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0004.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0004.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0004.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[37.351, 10.669, 57.672]} scale={0.831}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0005.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0005.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0005.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0005.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0005.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0005.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0005.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0005.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0005.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0005.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0005.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0005.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0005.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0005.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-57.825, -0.977, 82.012]} scale={0.943}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_tree_trunk_0006.geometry}
          material={materials.tree_trunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic10_lambert9_0006.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic11_lambert8_0006.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic12_lambert8_0006.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic13_lambert7_0006.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic14_lambert7_0006.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic15_lambert7_0006.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic16_lambert7_0006.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic17_lambert8_0006.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic18_lambert8_0006.geometry}
          material={materials.lambert8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic6_lambert9_0006.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic7_lambert9_0006.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic8_lambert9_0006.geometry}
          material={materials.lambert9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic9_lambert10_0006.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-9.717, -0.387, 59.38]} scale={1.141}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0.geometry}
          material={materials.lambert11}
        />
      </group>
      <group position={[6.393, -0.703, 26.225]} scale={1.724}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0001.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0001.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0001.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0001.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0001.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0001.geometry}
          material={materials.lambert11}
        />
      </group>
      <group position={[38.713, 18.74, 117.497]} scale={2.16}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0002.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0002.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0002.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0002.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0002.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0002.geometry}
          material={materials.lambert11}
        />
      </group>
      <group position={[47.346, 20.46, 28.362]} scale={2.439}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0003.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0003.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0003.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0003.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0003.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0003.geometry}
          material={materials.lambert11}
        />
      </group>
      <group position={[-4.537, 2.405, -7.426]} scale={1.724}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0004.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0004.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0004.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0004.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0004.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0004.geometry}
          material={materials.lambert11}
        />
      </group>
      <group position={[47.141, 23.225, 39.796]} scale={1.141}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert18_0005.geometry}
          material={materials.lambert18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic1_lambert11_0005.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic2_lambert11_0005.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic3_lambert11_0005.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic4_lambert11_0005.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlatonic5_lambert11_0005.geometry}
          material={materials.lambert11}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad1_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad2_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad3_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad4_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad5_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad6_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lilypad7_lambert23_0.geometry}
        material={materials.lambert23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.terrain_grass1_0.geometry}
        material={materials.grass1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.terrain_grass2_0.geometry}
        material={materials.grass2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.terrain_grass3_0.geometry}
        material={materials.grass3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.water_water1_0.geometry}
        material={materials.water1}
      />
    </group>
  )
}

useGLTF.preload('/models-3d/HomeRiver.glb')